blog/models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

__all__ = [
    "db",
]

blog/models/user.py
from sqlalchemy import Column, Integer, String, Boolean
from blog.models.database import db
from flask_login import UserMixin
from blog.security import flask_bcrypt


class User(db.Model):
    id = Column(Integer, primary_key=True)
    username = Column(String(80), unique=True, nullable=False)
    is_staff = Column(Boolean, nullable=False, default=False)

def __repr__(self):
    return f"<User #{self.id} {self.username!r}>"



class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)

email = Column(String(255), nullable=False, default="", server_default="")

_password = Column(LargeBinary, nullable=True)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, value):
        self._password = flask_bcrypt.generate_password_hash(value)

    def validate_password(self, password) -> bool:
        return flask_bcrypt.check_password_hash(self._password, password)


first_name = Column(String(120), unique=False, nullable=False, default="", server_default="")
last_name = Column(String(120), unique=False, nullable=False, default="", server_default="")
email = Column(String(255), unique=True, nullable=False, default="", server_default="")

blog/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField, SubmitField

class UserBaseForm(FlaskForm):
    first_name = StringField("First Name")
    last_name = StringField("Last Name")
    username = StringField(
        "username",
        [validators.DataRequired()],
    )
    email = StringField(
        "Email Address",
        [
            validators.DataRequired(),
            validators.Email(),
            validators.Length(min=6, max=200),
        ],
        filters=[lambda data: data and data.lower()],
    )

class RegistrationForm(UserBaseForm):
    password = PasswordField(
        "New Password",
    [
            validators.DataRequired(),
         validators.EqualTo("confirm", message="Passwords must match"),
    ],
)
confirm = PasswordField("Repeat Password")
submit = SubmitField("Register")

class LoginForm(FlaskForm):
    username = StringField(
        "username",
        [validators.DataRequired()],
    )
    password = PasswordField(
        "Password",
        [validators.DataRequired()],
    )
    submit = SubmitField("Login")

blog/app.py
from flask import Flask, g
from blog.user import views
from blog.models.database import db
from flask_migrate import Migrate
from blog.security import flask_bcrypt

def create_app() -> Flask:
    app = Flask(__name__)
    register_blueprints(app)
    return app

def register_blueprints(app: Flask):
    app.register_blueprint(views.user)


app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:////tmp/blog.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db.init_app(app)

cfg_name = os.environ.get("CONFIG_NAME") or "ProductionConfig"
app.config.from_object(f"blog.configs.{cfg_name}")
migrate = Migrate(app, db)
flask_bcrypt.init_app(app)

blog/user/views.py
from flask import Blueprint, render_templates, redirect
from werkzeug.exceptions import NotFound

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

USERS = {
    1: "Alice",
    2: "John",
    3: "Mike",
}


@user.route('/')
def user_list():
    return render_template(
        'users/list.html',
        users=USERS,
    )


@users_app.route('/<int:pk>/')
def get_user(pk: int):
    try:
        user_name = USERS[pk]
    except KeyError:
        raise NotFound(f'User id {pk} not found')
    return render_template(
        'users/details.html',
        user_name=user_name,
    )

@app.cli.command("init-db")
def init_db():
    db.create_all()
    print("done!")


@app.cli.command("create-users")
def create_users():
    from blog.models import User
    admin = User(username="admin", is_staff=True)
    james = User(username="james")
    db.session.add(admin)
    db.session.add(james)
    db.session.commit()
    print("done! created users:", admin, james)



@auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    if request.method == "GET":
    return render_template("auth/login.html")

    username = request.form.get("username")
    if not username:
        return render_template("auth/login.html", error="username not passed")

    user = User.query.filter_by(username=username).one_or_none()
    if user is None:
        return render_template("auth/login.html", error=f"no user {username!r}found")

    login_user(user)
    return redirect(url_for("index"))

blog/views/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import LoginManager, login_user, logout_user, login_required
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import NotFound

from blog.models.database import db
from blog.models import User
from blog.forms.user import RegistrationForm, LoginForm


auth_app = Blueprint("auth_app", __name__)

login_manager = LoginManager()
login_manager.login_view = "auth_app.login"

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()

@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("auth_app.login"))

@auth_app.route("/register/", methods=["GET", "POST"], endpoint="register")
def register():
    if current_user.is_authenticated:
        return redirect("index")

    error = None
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)

        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)

        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff=False,
        )

user.password = form.password.data
db.session.add(user)
try:
db.session.commit()
except IntegrityError:
current_app.logger.exception("Could not create user!")
error = "Could not create user!"
else:
current_app.logger.info("Created user %s", user)
login_user(user)
return redirect(url_for("index"))
return render_template("auth/register.html", form=form, error=error)


def login():
    return "WIP"

@auth_app.route("/login-as/", methods=["GET", "POST"], endpoint="login-as")
def login_as():
    if not (current_user.is_authenticated and current_user.is_staff):
    raise NotFound


def login():
    if current_user.is_authenticated:
        return redirect("index")

    form = LoginForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one_or_none()
        if user is None:
            return render_template("auth/login.html", form=form, error="username doesn't exist")
        if not user.validate_password(form.password.data):
            return render_template("auth/login.html", form=form, error="invalid username or password")

        login_user(user)
        return redirect(url_for("index"))
    return render_template("auth/login.html", form=form)

blog/views/users.py
from blog.models import User

    users_app = Blueprint("users_app", __name__)

@users_app.route("/", endpoint="list")
def users_list():
    users = User.query.all()
    return render_template("users/list.html", users=users)


@users_app.route("/<int:user_id>/", endpoint="details")
def user_details(user_id: int):
    user = User.query.filter_by(id=user_id).one_or_none()
    if user is None:
        raise NotFound(f"User #{user_id} doesn't exist!")

    return render_template("users/details.html", user=user)

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

      {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
      {% endblock %}
      <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
  {include 'navbar.html' %}
  <div class="container">
      {% block body %}{% endblock %}
  </div>




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}{% endblock %}
    </title>
    {% block css %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
    {% block js %}{% endblock %}
</body>
</html>




<div class="navbar-nav ms-auto">
    {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
    {% else %}
        <a href="{{ url_for('login') }}"
            class="nav-link {% if request.endpoint == 'login' -%}active{%- endif %}">
            Login
        </a>
    {% endif %}
</div>

{% for (endpoint, label) in [('auth_app.login', 'Login'), ('auth_app.register','Register')] %}
    <a href="{{ url_for(endpoint) }}"
            class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
        {{ label }}
    </a>
{% endfor %}

blog/templates/macro/formhelpers.html
{% macro render_field(field) %}
    <div class="row my-3">
        {{ field.label(class="col-sm-4 col-md-3 col-lg-2 col-form-label") }}
        <div class="col-sm-8 col-md-6">
            {{ field(class="form-control" + (" is-invalid" if field.errors else ""))|safe }}
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endmacro %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index') }}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                        <a class="nav-link" href="{{url_for('user.user_list') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Reports</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

blog/templates/users/details.html
{% extends 'base.html' %}

{% block title %}
    User #{{ user.id }}
{% endblock %}

{% block body %}
    <h1>
        {{ user.username }}
    </h1>
    {% if user.is_staff %}
    <span class="badge bg-secondary">staff</span>
{% endif %}
{% endblock %}

blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1>{{ user_name }}</h1>
    {% for user_id in users %}}
        <ul>
            <li>
            <a href="{{ url_for('user.get_user', pk=user_id) }}">{{ users[user_id] }}</a></li>
        </ul>
{% endblock %}